#!/usr/bin/env bash
# Dynamic Slurm worker node setup with NVIDIA GPU auto-detection.
set -Eeuo pipefail

if (( EUID != 0 )); then
  exec sudo bash "$0" "$@"
fi

ask() {
  local label="$1" default="${2:-}" value
  read -r -p "$label${default:+ [$default]}: " value
  printf '%s' "${value:-$default}"
}

default_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
default_node="$(hostname -s)"
old_controller="$(awk -F= '/^SlurmctldHost=/{print $2; exit}' /etc/slurm/slurm.conf 2>/dev/null || true)"
old_cluster="$(awk -F= '/^ClusterName=/{print $2; exit}' /etc/slurm/slurm.conf 2>/dev/null || true)"

echo '=== Dynamic Slurm worker + NVIDIA GPU setup ==='
controller="$(ask 'Controller IP or hostname' "${old_controller:-192.168.43.44}")"
cluster="$(ask 'Cluster name' "${old_cluster:-labcluster}")"
node_name="$(ask 'Worker node name' "$default_node")"
node_ip="$(ask 'Worker node IP' "$default_ip")"

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y munge slurmd slurm-client

has_gpu=0
if command -v nvidia-smi >/dev/null 2>&1; then
  apt-get install -y slurm-wlm-nvml-plugin
  has_gpu=1
fi

# Detect resources after the Slurm NVIDIA/NVML plugin is installed.
detected="$(slurmd -C 2>/dev/null || true)"
cpus="$(sed -n 's/.*CPUs=\([0-9][0-9]*\).*/\1/p' <<<"$detected" | head -1)"
memory="$(sed -n 's/.*RealMemory=\([0-9][0-9]*\).*/\1/p' <<<"$detected" | head -1)"
gpu_gres="$(sed -n 's/.*\(Gres=gpu:[^ ]*\).*/\1/p' <<<"$detected" | head -1)"
cpus="${cpus:-$(nproc)}"
memory="${memory:-$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)}"

install -d -o slurm -g slurm -m 0755 /var/spool/slurmd

cat > /etc/slurm/slurm.conf <<EOF
# Generated by setup-worker-node-gpu-dynamic.sh
ClusterName=$cluster
SlurmctldHost=$controller
SlurmctldPort=6817
SlurmUser=slurm
AuthType=auth/munge
MpiDefault=none
DebugFlags=NO_CONF_HASH
NodeName=$node_name NodeAddr=$node_ip CPUs=$cpus RealMemory=$memory State=UNKNOWN
EOF

if (( has_gpu == 1 )) && [[ -n "$gpu_gres" ]]; then
  printf 'GresTypes=gpu\n' >> /etc/slurm/slurm.conf
  cat > /etc/slurm/gres.conf <<'EOF'
AutoDetect=nvml
EOF
else
  rm -f /etc/slurm/gres.conf
fi

systemctl enable --now munge
systemctl restart slurmd

echo
echo '=== Worker setup complete ==='
echo "Worker: $node_name ($node_ip)"
echo "Detected: CPUs=$cpus RealMemory=${memory}M ${gpu_gres:-no GPU found}"
if (( has_gpu == 1 )) && [[ -n "$gpu_gres" ]]; then
  echo 'Put this on the CONTROLLER in /etc/slurm/slurm.conf:'
  echo "GresTypes=gpu"
  echo "NodeName=$node_name NodeAddr=$node_ip CPUs=$cpus RealMemory=$memory ${gpu_gres#Gres=} State=UNKNOWN"
  echo 'Then run: sudo scontrol reconfigure'
  echo
  slurmd -G || true
fi
systemctl --no-pager --full status slurmd | sed -n '1,12p'
